version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
        # Create missing modules and their directories if they don't exist
        - mkdir -p src/lib/teachers src/lib/pointSystem
        - cp -f src/lib/teachers.ts src/lib/teachers/index.ts || echo "export default {};" > src/lib/teachers/index.ts
        - cp -f src/lib/pointSystem.ts src/lib/pointSystem/index.ts || echo "export default {};" > src/lib/pointSystem/index.ts
        # Debug
        - echo "PostCSS Config:"
        - cat postcss.config.mjs
    build:
      commands:
        # Set up environment variables securely by checking for existence first
        - touch .env.local
        - "[ ! -z \"$MONGODB_URI\" ] && echo \"MONGODB_URI=$MONGODB_URI\" >> .env.local"
        - "[ ! -z \"$NEXTAUTH_URL\" ] && echo \"NEXTAUTH_URL=$NEXTAUTH_URL\" >> .env.local"
        - "[ ! -z \"$NEXTAUTH_SECRET\" ] && echo \"NEXTAUTH_SECRET=$NEXTAUTH_SECRET\" >> .env.local"
        - "[ ! -z \"$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME\" ] && echo \"NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME=$NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME\" >> .env.local"
        - "[ ! -z \"$NEXT_PUBLIC_CLOUDINARY_API_KEY\" ] && echo \"NEXT_PUBLIC_CLOUDINARY_API_KEY=$NEXT_PUBLIC_CLOUDINARY_API_KEY\" >> .env.local"
        - "[ ! -z \"$CLOUDINARY_API_SECRET\" ] && echo \"CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET\" >> .env.local"
        - "[ ! -z \"$DEEPSEEK_API_KEY\" ] && echo \"DEEPSEEK_API_KEY=$DEEPSEEK_API_KEY\" >> .env.local"
        - "[ ! -z \"$DEEPSEEK_BASE_URL\" ] && echo \"DEEPSEEK_BASE_URL=$DEEPSEEK_BASE_URL\" >> .env.local"
        - "[ ! -z \"$LOG_LEVEL\" ] && echo \"LOG_LEVEL=$LOG_LEVEL\" >> .env.local"
        - "[ ! -z \"$STRIPE_SECRET_KEY\" ] && echo \"STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY\" >> .env.local"
        - "[ ! -z \"$STRIPE_PUBLISHABLE_KEY\" ] && echo \"STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY\" >> .env.local"
        - "[ ! -z \"$STRIPE_WEBHOOK_SECRET\" ] && echo \"STRIPE_WEBHOOK_SECRET=$STRIPE_WEBHOOK_SECRET\" >> .env.local"
        - "[ ! -z \"$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY\" ] && echo \"NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY\" >> .env.local"
        - echo "NODE_ENV=production" >> .env.local
        - echo "AWS_REGION=$AWS_REGION" >> .env.local
        # Log environment variables were set (without showing values)
        - echo "Environment variables have been checked and set to .env.local"
        # Verify env file exists (without showing contents)
        - ls -la .env.local
        # Use our special build command for Amplify
        - cp postcss.config.amplify.js postcss.config.mjs
        - npm run build --no-lint
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/* 